"use client";

import { FaExclamationTriangle as AlertTriangle, FaExternalLinkAlt as ExternalLink, FaSpinner as LoaderCircle, FaClipboardList as ListChecks, FaRoute as Route } from "react-icons/fa";
import { useCallback, useEffect, useState } from "react";
import { EXTERNAL_LINKS } from "@/config/constants";
import { getApiError } from "@/lib/api/client";
import { getResponseGuidance } from "@/lib/api/deeptrace";
import type { ResponseGuidance } from "@/types";

/**
 * Case-specific next steps, generated by the backend from this case's own
 * findings. Every action names who performs it and what DeepTrace's part is, so
 * the tool's boundary stays explicit: it prepares evidence, it does not report
 * on the user's behalf.
 */
export function GuidancePanel({ investigationId, ready }: { investigationId: number; ready: boolean }) {
  const [guidance, setGuidance] = useState<ResponseGuidance | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      setGuidance(await getResponseGuidance(investigationId));
    } catch (guidanceError) {
      setError(getApiError(guidanceError, "Response guidance could not be generated."));
    } finally {
      setLoading(false);
    }
  }, [investigationId]);

  useEffect(() => {
    if (!ready) return;
    const timer = window.setTimeout(() => { void load(); }, 0);
    return () => window.clearTimeout(timer);
  }, [ready, load]);

  if (!ready) {
    return (
      <section className="content-card">
        <Heading priority={null} />
        <div className="inline-empty">
          <ListChecks size={19} /> Guidance is generated from completed findings. It will appear once analysis finishes.
        </div>
      </section>
    );
  }

  return (
    <section className="content-card">
      <Heading priority={guidance?.priority ?? null} />

      {loading && <div className="inline-empty"><LoaderCircle className="spin" size={18} /> Preparing guidance…</div>}
      {error && <div className="form-alert"><AlertTriangle size={18} /><span>{error}</span></div>}

      {guidance && (
        <>
          {guidance.case_findings.length > 0 && (
            <div className="findings-recap">
              <strong>What this case actually shows</strong>
              <ul>{guidance.case_findings.map((finding) => <li key={finding}>{finding}</li>)}</ul>
            </div>
          )}

          <ol className="guidance-steps">
            {guidance.recommended_actions.map((action) => (
              <li key={action.step}>
                <span>{action.step}</span>
                <div>
                  <strong>{action.action}</strong>
                  <p>{action.why}</p>
                  <div className="guidance-roles">
                    <span><b>Who acts:</b> {action.who_acts}</span>
                    <span><b>DeepTrace&rsquo;s part:</b> {action.deeptrace_role}</span>
                  </div>
                </div>
              </li>
            ))}
          </ol>

          {guidance.evidence_package.length > 0 && (
            <div className="package-block">
              <strong>Attach this to your report</strong>
              <ul>{guidance.evidence_package.map((item) => <li key={item}>{item}</li>)}</ul>
            </div>
          )}

          <div className="route-list">
            <div className="route-heading"><Route size={17} /> <strong>Official reporting routes</strong></div>
            {guidance.reporting_routes.map((route) => (
              <div className="route-row" key={route.route}>
                <strong>{route.route}</strong>
                <p>{route.detail}</p>
                <small>{route.who_acts}</small>
              </div>
            ))}
            <a className="btn btn-secondary" href={EXTERNAL_LINKS.cybercrimePortal} target="_blank" rel="noreferrer">
              Open cybercrime.gov.in <ExternalLink size={15} />
            </a>
          </div>

          <div className="boundary-box">
            <strong>DeepTrace&rsquo;s boundary</strong>
            <p>{guidance.deeptrace_boundary}</p>
            <ul>{guidance.caveats.map((caveat) => <li key={caveat}>{caveat}</li>)}</ul>
          </div>
        </>
      )}
    </section>
  );
}

function Heading({ priority }: { priority: string | null }) {
  return (
    <div className="content-card-heading">
      <div>
        <span>What to do next</span>
        <h2>Response and reporting guidance</h2>
      </div>
      {priority && <span className="count-badge"><ListChecks size={13} /> {priority} priority</span>}
    </div>
  );
}
