import { ImageOff, ScanSearch } from "lucide-react";
import { API_BASE_URL } from "@/config/constants";
import { clock, dataOf, num, rows, str } from "@/lib/modules";
import type { InvestigationDetail } from "@/types";

/**
 * Where the manipulation signal concentrated in time, and what the flagged
 * frames look like. Overlays are generated by the localization module from the
 * same per-frame scores shown in the manipulation panel — they highlight where
 * the detector responded, they do not prove an edit occurred there.
 */
export function SuspiciousFramesPanel({ investigation }: { investigation: InvestigationDetail }) {
  const result = investigation.analysis_results?.localization;
  if (!result) return null;

  const data = dataOf(investigation, "localization");
  const intervals = rows(data, "suspicious_intervals");
  const overlays = rows(data, "overlays");
  const regions = rows(data, "top_regions");
  const examined = num(data, "frames_examined");
  const flagged = num(data, "suspicious_frame_count");
  const threshold = num(data, "threshold");

  if (result.status !== "completed") {
    return (
      <section className="content-card">
        <PanelHeading count={null} />
        <div className="inline-empty">
          <ImageOff size={19} />
          {str(data, "reason") || str(data, "details") || "Manipulation localization did not run for this media."}
        </div>
        <p className="panel-note">
          An unavailable module is neither evidence of authenticity nor evidence of manipulation.
        </p>
      </section>
    );
  }

  return (
    <section className="content-card">
      <PanelHeading count={flagged} />
      <p className="panel-lead">
        {str(data, "summary") ||
          `${flagged ?? 0} of ${examined ?? 0} sampled frames scored at or above the ${threshold ?? 0.5} threshold.`}
      </p>

      {intervals.length > 0 && (
        <div className="interval-list">
          {intervals.map((interval, index) => (
            <div className="interval-row" key={`${interval.start_seconds}-${index}`}>
              <span className="interval-clock">{str(interval, "label") || clock(num(interval, "start_seconds"))}</span>
              <span className="interval-bar">
                <span style={{ width: `${Math.round((num(interval, "peak_signal") ?? 0) * 100)}%` }} />
              </span>
              <span className="interval-figure">
                peak {num(interval, "peak_signal") !== null ? (num(interval, "peak_signal") as number).toFixed(3) : "—"}
              </span>
              <small>{num(interval, "sample_count") ?? 0} sampled frame(s)</small>
            </div>
          ))}
        </div>
      )}

      {overlays.length > 0 ? (
        <div className="frame-gallery">
          {overlays.slice(0, 8).map((overlay, index) => {
            const path = str(overlay, "overlay_path");
            return (
              <figure key={`${path}-${index}`}>
                {path ? (
                  // A plain <img> on purpose: these are forensic artifacts served by the
                  // backend, and next/image would re-encode them. The bytes shown must be
                  // the bytes that were preserved and hashed.
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={`${API_BASE_URL}/${path}`} alt={`Flagged frame at ${str(overlay, "timestamp_label") || "unknown timestamp"}`} loading="lazy" />
                ) : (
                  <div className="frame-missing"><ImageOff size={18} /></div>
                )}
                <figcaption>
                  <strong>{str(overlay, "timestamp_label") || clock(num(overlay, "timestamp_seconds"))}</strong>
                  <span>score {num(overlay, "manipulation_signal")?.toFixed(3) ?? "—"}</span>
                </figcaption>
              </figure>
            );
          })}
        </div>
      ) : (
        <div className="inline-empty"><ImageOff size={19} /> No overlay previews were produced for this case.</div>
      )}

      {regions.length > 0 && (
        <details className="technical-details">
          <summary>Show the highest-scoring sampled regions</summary>
          <div className="mini-table">
            <div className="mini-table-head">
              <span>Timestamp</span><span>Score</span><span>Face located</span><span>Region</span>
            </div>
            {regions.slice(0, 10).map((region, index) => (
              <div className="mini-table-row" key={`${region.timestamp_seconds}-${index}`}>
                <span>{str(region, "timestamp_label") || clock(num(region, "timestamp_seconds"))}</span>
                <span>{num(region, "manipulation_signal")?.toFixed(4) ?? "—"}</span>
                <span>{region.face_detected ? str(region, "face_source") || "yes" : "no"}</span>
                <span>{str(region, "region_note") || "—"}</span>
              </div>
            ))}
          </div>
        </details>
      )}

      <p className="panel-note">
        {str(data, "interpretation") ||
          "Timestamps mark sampled frames whose score crossed the threshold. They indicate where to look, not what happened."}
      </p>
    </section>
  );
}

function PanelHeading({ count }: { count: number | null }) {
  return (
    <div className="content-card-heading">
      <div>
        <span>Where the signal concentrated</span>
        <h2>Flagged frames and timestamps</h2>
      </div>
      <span className="count-badge">
        <ScanSearch size={13} /> {count === null ? "not available" : `${count} flagged`}
      </span>
    </div>
  );
}
